---
title: "ebounds_table"
format: html
editor: visual
---

```{r}
#| message: false
library(eete)
library(tidyverse)
```

## Check that ebounds using $\gamma = 0$ matches Stata program

```{r}
data("JC_Data_IADB_Sample_Selection", package = "eete") 

JC_Data_IADB_Sample_Selection = JC_Data_IADB_Sample_Selection |>
  mutate(lnwage208 = exp(lnwage208))

ebounds(crpie, gam = 0, y = "lnwage208", d = "emp208", z = "treatmnt", wgt = "dsgn_wgt", data = JC_Data_IADB_Sample_Selection, minimum_y = exp(0.9), maximum_y = exp(2.77))
```

## Check that ebounds using $\gamma = 2$ matches Stata program

```{r}
ebounds(crpie, gam = 2, y = "lnwage208", d = "emp208", z = "treatmnt", wgt = "dsgn_wgt", data = JC_Data_IADB_Sample_Selection, minimum_y = exp(0.9), maximum_y = exp(2.77))
```

## Run program to create dataframe of bounds

```{r}

gam_list = seq(0.01, 5, by = 0.01)

bounds_long = ebounds(crpie, gam = 0, y = "lnwage208", d = "emp208", z = "treatmnt", wgt = "dsgn_wgt", data = JC_Data_IADB_Sample_Selection, minimum_y = exp(0.9), maximum_y = exp(2.77))

bounds = bounds_long |>
  pivot_wider(names_from = Bounds, 
              values_from = c(ee_L_a, ee_U_a, ee_L_b, ee_U_b),
              names_sep = "_") |>
  mutate(gam = 0) |>
  relocate(gam, .before = everything())



for (gamma in gam_list){
  bounds_long = ebounds(crpie, gam = gamma, y = "lnwage208", d = "emp208", z = "treatmnt", wgt = "dsgn_wgt", data = JC_Data_IADB_Sample_Selection, minimum_y = exp(0.9), maximum_y = exp(2.77))

  bounds_row = bounds_long |>
    pivot_wider(names_from = Bounds, 
                values_from = c(ee_L_a, ee_U_a, ee_L_b, ee_U_b),
                names_sep = "_") |>
    mutate(gam = gamma) |>
    relocate(gam, .before = everything())
  
  bounds = rbind(bounds, bounds_row)
  
}

```

```{r}
write.csv(bounds,"bounds.csv", row.names = FALSE)
```

